### ISSUE TITLE
Zero on start X value

### ISSUE THREAD

**Issue by Ensase** [sgreben/piecewiselinear#1]
Hello! 
I've tried to run simple example before using in project:

`f := piecewiselinear.Function{Y: []float64{100, 105, 120}}`
`	f.X = piecewiselinear.Span(10, 16, len(f.Y))`
`	fmt.Println(f.X)`
`	fmt.Println(f.Y)`
`	fmt.Println(`
`		f.At(10), // f.At(x) evaluates f at x`
`		f.At(11),`
`		f.At(12),`
`		f.At(13),`
`		f.At(14),`
`		f.At(15),`
`		f.At(16),`
`	)`

And I've got the output:
`[10 13 16]`
`[100 105 120]`
`0 101.66666666666667 103.33333333333334 105 110.00000000000001 115 120`

Everything is fine except zero on defined X value.

Thank you

**Comment by sgreben** [comment]
Good catch, thanks! I've just pushed a fix and a test that should catch this case :) Tagged as release `2.0.4` now.

**Comment by sgreben** [comment]
I've also double-checked the output of the fixed code for your specific example:

<img width="765" alt="Screen Shot 2019-08-25 at 00 28 08" src="https://user-images.githubusercontent.com/3280753/63643376-4e8e7680-c6cf-11e9-91a3-f0b224766a1e.png">

**Comment by sgreben** [comment]
For convenience, here's the link to the release with the fix: https://github.com/sgreben/piecewiselinear/releases/tag/2.0.4 :)

**Comment by Ensase** [comment]
All works fine.
Thanks a lot!

**Comment by sgreben** [comment]
You're welcome! Thanks for finding the bug 👍
